export const mapsConfig = {
    GOOGLE_PLACES_API_KEY: " AIzaSyCSGK_yxwENxg4vH4KnFOnKYDyKibyU1NQ",
    GOOGLE_GEOLOCATION_API_KEY: "AIzaSyCSGK_yxwENxg4vH4KnFOnKYDyKibyU1NQ",
    GOOGLE_MAPS_API_KEY: "AIzaSyCkA4JGcpYCNWfZuG9xv2DeOE1Uk05vi24",
    JAVASCRIPT_MAPS_API_KEY: "AIzaSyCSGK_yxwENxg4vH4KnFOnKYDyKibyU1NQ"
}